# docker-compose.yml

version: "3"

services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - .pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles

# docker-compose up --build --force-reacreate
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: web
#    restart: always
#    volumes:
#      - ./:/app
#      - /app/node_modules
#      - /app/.next
#    ports:
#      - 3000:3000
