version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: auth
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html/backend
      - enlive-vendor:/var/www/html/backend/vendor
    depends_on:
      - db
    networks:
      - app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./fr
      - ontend:/var/www/html/frontend
    depends_on:
      - backend
    networks:
      - app

  db:
    container_name: db
    image: mysql:5.7.32
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'auth'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - app


networks:
  app:
    driver: bridge
volumes:
  enlive-vendor:
